development:
  adapter: mysql2
  database: opstat
  host: 127.0.0.1
  username: root
  password: gfe%Q:+!
production:
  adapter: mysql2
  database: opstat
  host: 127.0.0.1
  username: root
  password: gfe%Q:+!
