development:
  adapter: mysql2
  database: opstat
  host: 127.0.0.1
  username: root
  password: dEtV<jcg$6MQ
production:
  adapter: mysql2
  database: opstat
  host: 127.0.0.1
  username: root
  password: dEtV<jcg$6MQ
