defaults: &defaults
  host: 10.5.0.10
  port: 27017
  op_timeout: 60

development:
  <<: *defaults
  database: opstat_gui_development

test:
  <<: *defaults
  database: opstat_gui_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: opstat_gui_development
#  username: <%= ENV['MONGO_USERNAME'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
